name = "MTcubeSMP"
author = "Matix732"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b9e1c12aba55556430732679831bac7ebb59cf53f17f930127ad94e8c6161686"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
