name = "MTcubeSMP"
author = "Matix732"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aafa13dc4b176897b79b69ee83afd004f6b141827156e8a3df2a88e9025d448e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"
